# Generated by Django 4.1.7 on 2023-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_civil_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='civil_faculty',
            name='Email_Id',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civil_faculty',
            name='Experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='civil_faculty',
            name='Qualifications',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='civil_faculty',
            name='photo',
            field=models.ImageField(default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='civil_faculty',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
