# Generated by Django 4.1.7 on 2023-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_civil_faculty_email_id_civil_faculty_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aiml_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('Qualifications', models.CharField(max_length=50, null=True)),
                ('Experience', models.CharField(max_length=50, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('Email_Id', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cs_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('Qualifications', models.CharField(max_length=50, null=True)),
                ('Experience', models.CharField(max_length=50, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('Email_Id', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electrical_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('Qualifications', models.CharField(max_length=50, null=True)),
                ('Experience', models.CharField(max_length=50, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('Email_Id', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='entc_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('Qualifications', models.CharField(max_length=50, null=True)),
                ('Experience', models.CharField(max_length=50, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('Email_Id', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('Qualifications', models.CharField(max_length=50, null=True)),
                ('Experience', models.CharField(max_length=50, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('Email_Id', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
