# Generated by Django 4.1.7 on 2023-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_aiml_faculty_cs_faculty_electrical_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nss_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxvAsTIDLPrAsCWYxv9DS7xQjPlRS0SelfWkTe0TAtUA&s', upload_to='')),
                ('description', models.CharField(max_length=700)),
            ],
        ),
    ]
