# Generated by Django 4.1.7 on 2023-04-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_nss_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nss_photo',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
