# Generated by Django 4.1.7 on 2023-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_alter_nss_photo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='elibrary_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eBooks', models.CharField(max_length=100)),
                ('url_eBooks', models.CharField(max_length=200)),
            ],
        ),
    ]
