# Generated by Django 4.1.7 on 2023-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_elibrary_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='e_Books_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_Books', models.CharField(max_length=70)),
                ('Link', models.CharField(max_length=70)),
                ('Particular', models.CharField(max_length=70)),
            ],
        ),
    ]
