# Generated by Django 4.1.7 on 2023-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_e_books_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=70)),
                ('m_name', models.CharField(max_length=70)),
                ('l_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('library_id', models.CharField(max_length=70)),
                ('contact_no', models.IntegerField()),
                ('department', models.CharField(max_length=70)),
                ('year', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
