# Generated by Django 4.1.7 on 2023-04-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nss_photo',
        ),
    ]
