# Generated by Django 4.1.7 on 2023-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_nss_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nss_photo',
            name='photos',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
