# Generated by Django 4.1.7 on 2023-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_student_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='civil_faculty',
            new_name='faculty',
        ),
        migrations.DeleteModel(
            name='aiml_faculty',
        ),
        migrations.DeleteModel(
            name='cs_faculty',
        ),
        migrations.DeleteModel(
            name='electrical_faculty',
        ),
        migrations.DeleteModel(
            name='entc_faculty',
        ),
        migrations.DeleteModel(
            name='mechanical_faculty',
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='https://tse4.mm.bing.net/th?id=OIP.OesLvyzDO6AvU_hYUAT4IAHaHa&pid=Api&P=0', null=True, upload_to=''),
        ),
    ]
