# Generated by Django 4.1.7 on 2023-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_rename_civil_faculty_faculty_delete_aiml_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
