# Generated by Django 4.1.7 on 2023-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_faculty_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
