# Generated by Django 4.1.7 on 2023-04-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0016_faculty_password_faculty_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
    ]
