# Generated by Django 4.1.7 on 2023-04-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0017_remove_faculty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='l_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='m_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
