# Generated by Django 4.1.7 on 2023-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0018_faculty_f_name_faculty_l_name_faculty_m_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_notes', models.FileField(default='file is not available', upload_to='')),
            ],
        ),
    ]
