# Generated by Django 4.1.7 on 2023-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0019_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
