# Generated by Django 4.1.7 on 2023-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0020_alter_student_sem_alter_subject_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(default=0),
        ),
    ]
