# Generated by Django 4.1.7 on 2023-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0021_alter_student_sem_alter_subject_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
