# Generated by Django 4.1.7 on 2023-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0022_alter_student_sem_alter_subject_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_notes',
            field=models.FileField(default='file is not available', upload_to='doc/'),
        ),
    ]
