# Generated by Django 4.1.7 on 2023-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0023_alter_subject_sub_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_notes',
            field=models.FileField(null=True, upload_to='doc/'),
        ),
    ]
