# Generated by Django 4.1.7 on 2023-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0024_alter_subject_sub_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='depatment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
