# Generated by Django 4.1.7 on 2023-04-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0025_subject_depatment_alter_subject_sub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='depatment',
            new_name='department',
        ),
    ]
