# Generated by Django 4.1.7 on 2023-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0026_rename_depatment_subject_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('library_id', models.CharField(max_length=50)),
                ('att_check', models.BooleanField()),
            ],
        ),
    ]
