# Generated by Django 4.1.7 on 2023-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0027_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
