# Generated by Django 4.1.7 on 2023-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0029_sem4'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=3)),
                ('subject1', models.CharField(max_length=20)),
                ('subject2', models.CharField(max_length=20)),
                ('subject3', models.CharField(max_length=20)),
                ('subject4', models.CharField(max_length=20)),
                ('subject5', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='sem4',
        ),
    ]
