# Generated by Django 4.1.7 on 2023-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0030_sem_delete_sem4'),
    ]

    operations = [
        migrations.CreateModel(
            name='aicte_approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('aicte_file', models.FileField(null=True, upload_to='doc/')),
            ],
        ),
    ]
