# Generated by Django 4.1.7 on 2023-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0031_aicte_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_discription', models.CharField(max_length=70)),
                ('event_file', models.FileField(null=True, upload_to='doc/')),
            ],
        ),
        migrations.CreateModel(
            name='notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=50)),
                ('notice_discription', models.CharField(max_length=70)),
                ('notice_file', models.FileField(null=True, upload_to='doc/')),
            ],
        ),
    ]
