# Generated by Django 4.1.7 on 2023-06-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0032_event_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='program',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
