# Generated by Django 4.1.7 on 2023-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0033_faculty_designation_faculty_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='program',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
