# Generated by Django 4.1.7 on 2023-06-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0035_sppu_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='mandatory_disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('sppu_file', models.FileField(null=True, upload_to='doc/')),
            ],
        ),
    ]
