# Generated by Django 4.1.7 on 2023-06-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0036_mandatory_disclosure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandatory_disclosure',
            old_name='sppu_file',
            new_name='mandatory_file',
        ),
    ]
