# Generated by Django 4.1.7 on 2023-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0037_rename_sppu_file_mandatory_disclosure_mandatory_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='engadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mbaadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pharmadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='polyadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
    ]
