# Generated by Django 4.1.7 on 2023-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0038_engadmission_mbaadmission_pharmadmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='engadmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mbaadmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pharmadmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='polyadmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=80)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gendar', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='engadmission',
        ),
        migrations.DeleteModel(
            name='mbaadmission',
        ),
        migrations.DeleteModel(
            name='pharmadmission',
        ),
        migrations.DeleteModel(
            name='polyadmission',
        ),
    ]
