# Generated by Django 4.1.7 on 2023-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0039_engadmission_model_mbaadmission_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='b_pharm_facultys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('DOJ', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='d_pharm_facultys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('DOJ', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='m_pharm_facultys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('DOJ', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
    ]
