# Generated by Django 4.1.7 on 2023-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0040_b_pharm_facultys_d_pharm_facultys_m_pharm_facultys'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='DOJ',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
